### ISSUE TITLE
Calendar integration 

### ISSUE THREAD

**Issue by ghost** [forrestguice/SolunarPeriods#6]
Tapping Calendar integration immediately makes SunTimes stop.

**Comment by forrestguice** [comment]
Thanks for reporting.
I traced this bug to changes made in Suntimes `v0.15.2`.
It should be fixed with Suntimes `v0.15.6`, or with SolunarPeriods `v0.2.1` (both should be released within a few weeks).

In the meantime, the "calendar integration" itself should work if SuntimesCalendars is installed; a "Solunar Periods" entry will be listed in that app.

**Comment by ghost** [comment]
How many thanks?

**Comment by forrestguice** [comment]
> How many thanks?

Sorry, not sure I understand. How many what? Weeks until next release? 

I try to keep Suntimes on a 2 to 3 week cycle. I just tagged `v0.15.5`, so it will most likely be ~3 weeks until `v0.15.6`. SolunarPeriods isn't on a fixed schedule, but I need to make other changes before tagging `v0.2.1` (so likely the same schedule). It's very much dependent on availability of free time. Any replies here are similar - I don't usually check the tracker every day, but will try to respond to comments within a week.

Regarding this bug, its only the menu item that is broken. Clicking it should transition to the SuntimesCalendar app (but instead crashes). The "calendar integration" itself shouldn't have any issues (but you'll need to open the other app on your own).

**Comment by ghost** [comment]
Are you saying the button does nothing for calendar integration but only
forwards to Suntimes calendar integration?

**Comment by forrestguice** [comment]
Yes. It's just a link into the other application, or the F-Droid download if not installed.

When both apps are installed together, the "Suntimes Calendars" app will include a "Solunar Periods" option that can be toggled on/off. This is where the actual calendar integration happens.

**Comment by ghost** [comment]
Got it, I'll check it out.
